#[cfg(feature = "alternative-backends")]
pub mod agent_backends;
#[cfg(not(feature = "alternative-backends"))]
#[path = "agent_backends_disabled.rs"]
pub mod agent_backends;
pub mod apps;
pub mod auth;
pub mod boot;
pub mod cesp;
pub mod chat;
pub mod claude_flags;
pub mod cli;
pub mod community;
pub mod data;
#[cfg(debug_assertions)]
pub mod debug;
pub mod devtools;
pub mod diagnostics;
pub mod dialog;
pub mod diff;
pub mod env;
pub mod files;
pub mod grammars;
pub mod mcp;
pub mod metrics;
pub mod pinned_prompts;
pub mod plan;
pub mod plugin;
pub mod plugins_runtime;
pub mod remote;
pub mod repository;
pub mod scm;
pub mod settings;
pub mod shell;
pub mod slash_commands;
pub mod terminal;
pub mod updater;
pub mod usage;
pub mod voice;
pub mod workspace;
