#![allow(dead_code)]

/// Bundled Lucide icons (ISC license).
/// Each entry is (name, svg_content).
static ICONS: &[(&str, &str)] = &[
    ("minus", include_str!("../assets/icons/minus.svg")),
    ("check", include_str!("../assets/icons/check.svg")),
    ("circle", include_str!("../assets/icons/circle.svg")),
    ("mountain", include_str!("../assets/icons/mountain.svg")),
    ("plus", include_str!("../assets/icons/plus.svg")),
    ("navigation", include_str!("../assets/icons/navigation.svg")),
    ("x", include_str!("../assets/icons/x.svg")),
    ("square", include_str!("../assets/icons/square.svg")),
    ("terminal", include_str!("../assets/icons/terminal.svg")),
    ("code", include_str!("../assets/icons/code.svg")),
    (
        "thermometer",
        include_str!("../assets/icons/thermometer.svg"),
    ),
    ("clock", include_str!("../assets/icons/clock.svg")),
    ("egg", include_str!("../assets/icons/egg.svg")),
    (
        "circle-check",
        include_str!("../assets/icons/circle-check.svg"),
    ),
    ("cloud", include_str!("../assets/icons/cloud.svg")),
    ("search", include_str!("../assets/icons/search.svg")),
    ("power", include_str!("../assets/icons/power.svg")),
    ("gauge", include_str!("../assets/icons/gauge.svg")),
    ("circle-dot", include_str!("../assets/icons/circle-dot.svg")),
    ("infinity", include_str!("../assets/icons/infinity.svg")),
    ("tv", include_str!("../assets/icons/tv.svg")),
    (
        "git-commit-vertical",
        include_str!("../assets/icons/git-commit-vertical.svg"),
    ),
    ("triangle", include_str!("../assets/icons/triangle.svg")),
    ("battery", include_str!("../assets/icons/battery.svg")),
    ("circle-x", include_str!("../assets/icons/circle-x.svg")),
    ("code-xml", include_str!("../assets/icons/code-xml.svg")),
    ("dice-1", include_str!("../assets/icons/dice-1.svg")),
    ("info", include_str!("../assets/icons/info.svg")),
    ("command", include_str!("../assets/icons/command.svg")),
    ("at-sign", include_str!("../assets/icons/at-sign.svg")),
    (
        "flask-round",
        include_str!("../assets/icons/flask-round.svg"),
    ),
    ("user", include_str!("../assets/icons/user.svg")),
    ("library", include_str!("../assets/icons/library.svg")),
    ("pocket", include_str!("../assets/icons/pocket.svg")),
    ("music", include_str!("../assets/icons/music.svg")),
    ("lock-open", include_str!("../assets/icons/lock-open.svg")),
    ("grid-2x2", include_str!("../assets/icons/grid-2x2.svg")),
    ("lock", include_str!("../assets/icons/lock.svg")),
    ("book", include_str!("../assets/icons/book.svg")),
    ("beaker", include_str!("../assets/icons/beaker.svg")),
    ("ungroup", include_str!("../assets/icons/ungroup.svg")),
    ("git-branch", include_str!("../assets/icons/git-branch.svg")),
    ("git-merge", include_str!("../assets/icons/git-merge.svg")),
    ("flame", include_str!("../assets/icons/flame.svg")),
    ("target", include_str!("../assets/icons/target.svg")),
    ("merge", include_str!("../assets/icons/merge.svg")),
    ("rss", include_str!("../assets/icons/rss.svg")),
    ("mail", include_str!("../assets/icons/mail.svg")),
    (
        "highlighter",
        include_str!("../assets/icons/highlighter.svg"),
    ),
    ("download", include_str!("../assets/icons/download.svg")),
    ("share", include_str!("../assets/icons/share.svg")),
    ("upload", include_str!("../assets/icons/upload.svg")),
    ("briefcase", include_str!("../assets/icons/briefcase.svg")),
    ("brackets", include_str!("../assets/icons/brackets.svg")),
    (
        "square-code",
        include_str!("../assets/icons/square-code.svg"),
    ),
    ("history", include_str!("../assets/icons/history.svg")),
    ("barcode", include_str!("../assets/icons/barcode.svg")),
    ("tent", include_str!("../assets/icons/tent.svg")),
    ("timer", include_str!("../assets/icons/timer.svg")),
    (
        "git-commit-horizontal",
        include_str!("../assets/icons/git-commit-horizontal.svg"),
    ),
    ("database", include_str!("../assets/icons/database.svg")),
    ("calendar", include_str!("../assets/icons/calendar.svg")),
    ("globe", include_str!("../assets/icons/globe.svg")),
    (
        "external-link",
        include_str!("../assets/icons/external-link.svg"),
    ),
    (
        "circle-alert",
        include_str!("../assets/icons/circle-alert.svg"),
    ),
    ("anchor", include_str!("../assets/icons/anchor.svg")),
    ("moon", include_str!("../assets/icons/moon.svg")),
    ("test-tube", include_str!("../assets/icons/test-tube.svg")),
    ("zoom-out", include_str!("../assets/icons/zoom-out.svg")),
    ("wind", include_str!("../assets/icons/wind.svg")),
    ("copy", include_str!("../assets/icons/copy.svg")),
    (
        "message-square",
        include_str!("../assets/icons/message-square.svg"),
    ),
    ("archive", include_str!("../assets/icons/archive.svg")),
    ("trash", include_str!("../assets/icons/trash.svg")),
    ("bookmark", include_str!("../assets/icons/bookmark.svg")),
    ("folder", include_str!("../assets/icons/folder.svg")),
    (
        "search-code",
        include_str!("../assets/icons/search-code.svg"),
    ),
    ("paperclip", include_str!("../assets/icons/paperclip.svg")),
    ("hexagon", include_str!("../assets/icons/hexagon.svg")),
    (
        "triangle-alert",
        include_str!("../assets/icons/triangle-alert.svg"),
    ),
    ("monitor", include_str!("../assets/icons/monitor.svg")),
    ("headphones", include_str!("../assets/icons/headphones.svg")),
    (
        "message-circle",
        include_str!("../assets/icons/message-circle.svg"),
    ),
    ("utensils", include_str!("../assets/icons/utensils.svg")),
    (
        "ice-cream-cone",
        include_str!("../assets/icons/ice-cream-cone.svg"),
    ),
    ("video", include_str!("../assets/icons/video.svg")),
    ("compass", include_str!("../assets/icons/compass.svg")),
    ("ghost", include_str!("../assets/icons/ghost.svg")),
    ("workflow", include_str!("../assets/icons/workflow.svg")),
    (
        "satellite-dish",
        include_str!("../assets/icons/satellite-dish.svg"),
    ),
    ("shell", include_str!("../assets/icons/shell.svg")),
    ("clipboard", include_str!("../assets/icons/clipboard.svg")),
    (
        "git-compare",
        include_str!("../assets/icons/git-compare.svg"),
    ),
    (
        "git-pull-request",
        include_str!("../assets/icons/git-pull-request.svg"),
    ),
    ("grid-3x3", include_str!("../assets/icons/grid-3x3.svg")),
    ("key", include_str!("../assets/icons/key.svg")),
    (
        "tree-deciduous",
        include_str!("../assets/icons/tree-deciduous.svg"),
    ),
    ("diamond", include_str!("../assets/icons/diamond.svg")),
    ("wifi", include_str!("../assets/icons/wifi.svg")),
    ("image", include_str!("../assets/icons/image.svg")),
    ("link", include_str!("../assets/icons/link.svg")),
    ("map-pin", include_str!("../assets/icons/map-pin.svg")),
    ("eye", include_str!("../assets/icons/eye.svg")),
    ("umbrella", include_str!("../assets/icons/umbrella.svg")),
    ("wine", include_str!("../assets/icons/wine.svg")),
    ("antenna", include_str!("../assets/icons/antenna.svg")),
    ("pentagon", include_str!("../assets/icons/pentagon.svg")),
    ("plug", include_str!("../assets/icons/plug.svg")),
    (
        "git-pull-request-draft",
        include_str!("../assets/icons/git-pull-request-draft.svg"),
    ),
    ("bike", include_str!("../assets/icons/bike.svg")),
    ("variable", include_str!("../assets/icons/variable.svg")),
    (
        "folder-closed",
        include_str!("../assets/icons/folder-closed.svg"),
    ),
    ("scan", include_str!("../assets/icons/scan.svg")),
    ("leaf", include_str!("../assets/icons/leaf.svg")),
    ("flag", include_str!("../assets/icons/flag.svg")),
    ("lightbulb", include_str!("../assets/icons/lightbulb.svg")),
    ("scissors", include_str!("../assets/icons/scissors.svg")),
    ("file", include_str!("../assets/icons/file.svg")),
    ("hash", include_str!("../assets/icons/hash.svg")),
    ("heart", include_str!("../assets/icons/heart.svg")),
    (
        "shopping-cart",
        include_str!("../assets/icons/shopping-cart.svg"),
    ),
    ("award", include_str!("../assets/icons/award.svg")),
    (
        "git-pull-request-closed",
        include_str!("../assets/icons/git-pull-request-closed.svg"),
    ),
    ("notebook", include_str!("../assets/icons/notebook.svg")),
    ("zoom-in", include_str!("../assets/icons/zoom-in.svg")),
    ("pencil", include_str!("../assets/icons/pencil.svg")),
    ("book-open", include_str!("../assets/icons/book-open.svg")),
    ("coffee", include_str!("../assets/icons/coffee.svg")),
    ("zap", include_str!("../assets/icons/zap.svg")),
    ("bot", include_str!("../assets/icons/bot.svg")),
    ("braces", include_str!("../assets/icons/braces.svg")),
    ("badge", include_str!("../assets/icons/badge.svg")),
    ("eraser", include_str!("../assets/icons/eraser.svg")),
    (
        "flask-conical",
        include_str!("../assets/icons/flask-conical.svg"),
    ),
    ("house", include_str!("../assets/icons/house.svg")),
    ("users", include_str!("../assets/icons/users.svg")),
    ("regex", include_str!("../assets/icons/regex.svg")),
    ("shield", include_str!("../assets/icons/shield.svg")),
    ("feather", include_str!("../assets/icons/feather.svg")),
    ("inbox", include_str!("../assets/icons/inbox.svg")),
    ("milestone", include_str!("../assets/icons/milestone.svg")),
    ("trash-2", include_str!("../assets/icons/trash-2.svg")),
    ("git-fork", include_str!("../assets/icons/git-fork.svg")),
    ("bell", include_str!("../assets/icons/bell.svg")),
    ("send", include_str!("../assets/icons/send.svg")),
    (
        "database-zap",
        include_str!("../assets/icons/database-zap.svg"),
    ),
    ("sprout", include_str!("../assets/icons/sprout.svg")),
    ("brush", include_str!("../assets/icons/brush.svg")),
    (
        "thumbs-down",
        include_str!("../assets/icons/thumbs-down.svg"),
    ),
    ("thumbs-up", include_str!("../assets/icons/thumbs-up.svg")),
    ("box", include_str!("../assets/icons/box.svg")),
    (
        "folder-open",
        include_str!("../assets/icons/folder-open.svg"),
    ),
    (
        "message-circle-code",
        include_str!("../assets/icons/message-circle-code.svg"),
    ),
    ("tree-pine", include_str!("../assets/icons/tree-pine.svg")),
    (
        "circuit-board",
        include_str!("../assets/icons/circuit-board.svg"),
    ),
    ("cookie", include_str!("../assets/icons/cookie.svg")),
    ("dribbble", include_str!("../assets/icons/dribbble.svg")),
    ("binary", include_str!("../assets/icons/binary.svg")),
    (
        "library-big",
        include_str!("../assets/icons/library-big.svg"),
    ),
    (
        "badge-check",
        include_str!("../assets/icons/badge-check.svg"),
    ),
    (
        "folder-code",
        include_str!("../assets/icons/folder-code.svg"),
    ),
    ("server", include_str!("../assets/icons/server.svg")),
    ("globe-lock", include_str!("../assets/icons/globe-lock.svg")),
    ("logs", include_str!("../assets/icons/logs.svg")),
    ("apple", include_str!("../assets/icons/apple.svg")),
    ("citrus", include_str!("../assets/icons/citrus.svg")),
    ("wrench", include_str!("../assets/icons/wrench.svg")),
    ("banana", include_str!("../assets/icons/banana.svg")),
    ("glasses", include_str!("../assets/icons/glasses.svg")),
    ("orbit", include_str!("../assets/icons/orbit.svg")),
    ("plane", include_str!("../assets/icons/plane.svg")),
    (
        "sliders-horizontal",
        include_str!("../assets/icons/sliders-horizontal.svg"),
    ),
    (
        "sliders-vertical",
        include_str!("../assets/icons/sliders-vertical.svg"),
    ),
    ("skull", include_str!("../assets/icons/skull.svg")),
    ("bird", include_str!("../assets/icons/bird.svg")),
    ("folder-git", include_str!("../assets/icons/folder-git.svg")),
    ("podcast", include_str!("../assets/icons/podcast.svg")),
    ("gem", include_str!("../assets/icons/gem.svg")),
    ("snail", include_str!("../assets/icons/snail.svg")),
    ("gift", include_str!("../assets/icons/gift.svg")),
    (
        "thermometer-sun",
        include_str!("../assets/icons/thermometer-sun.svg"),
    ),
    (
        "train-front",
        include_str!("../assets/icons/train-front.svg"),
    ),
    ("signpost", include_str!("../assets/icons/signpost.svg")),
    ("youtube", include_str!("../assets/icons/youtube.svg")),
    (
        "heart-pulse",
        include_str!("../assets/icons/heart-pulse.svg"),
    ),
    ("microscope", include_str!("../assets/icons/microscope.svg")),
    ("tag", include_str!("../assets/icons/tag.svg")),
    ("megaphone", include_str!("../assets/icons/megaphone.svg")),
    ("film", include_str!("../assets/icons/film.svg")),
    ("hourglass", include_str!("../assets/icons/hourglass.svg")),
    ("turtle", include_str!("../assets/icons/turtle.svg")),
    (
        "folder-git-2",
        include_str!("../assets/icons/folder-git-2.svg"),
    ),
    (
        "construction",
        include_str!("../assets/icons/construction.svg"),
    ),
    (
        "folder-archive",
        include_str!("../assets/icons/folder-archive.svg"),
    ),
    ("camera", include_str!("../assets/icons/camera.svg")),
    ("phone", include_str!("../assets/icons/phone.svg")),
    ("radio", include_str!("../assets/icons/radio.svg")),
    ("webhook", include_str!("../assets/icons/webhook.svg")),
    ("building-2", include_str!("../assets/icons/building-2.svg")),
    ("trees", include_str!("../assets/icons/trees.svg")),
    ("hospital", include_str!("../assets/icons/hospital.svg")),
    ("test-tubes", include_str!("../assets/icons/test-tubes.svg")),
    ("castle", include_str!("../assets/icons/castle.svg")),
    ("wand", include_str!("../assets/icons/wand.svg")),
    ("file-code", include_str!("../assets/icons/file-code.svg")),
    ("file-text", include_str!("../assets/icons/file-text.svg")),
    ("files", include_str!("../assets/icons/files.svg")),
    ("network", include_str!("../assets/icons/network.svg")),
    ("package", include_str!("../assets/icons/package.svg")),
    ("landmark", include_str!("../assets/icons/landmark.svg")),
    ("warehouse", include_str!("../assets/icons/warehouse.svg")),
    ("pin", include_str!("../assets/icons/pin.svg")),
    ("codepen", include_str!("../assets/icons/codepen.svg")),
    ("popcorn", include_str!("../assets/icons/popcorn.svg")),
    ("octagon", include_str!("../assets/icons/octagon.svg")),
    ("pipette", include_str!("../assets/icons/pipette.svg")),
    ("ruler", include_str!("../assets/icons/ruler.svg")),
    ("crown", include_str!("../assets/icons/crown.svg")),
    ("hand-metal", include_str!("../assets/icons/hand-metal.svg")),
    ("truck", include_str!("../assets/icons/truck.svg")),
    ("earth", include_str!("../assets/icons/earth.svg")),
    (
        "message-circle-heart",
        include_str!("../assets/icons/message-circle-heart.svg"),
    ),
    ("toolbox", include_str!("../assets/icons/toolbox.svg")),
    (
        "database-backup",
        include_str!("../assets/icons/database-backup.svg"),
    ),
    ("group", include_str!("../assets/icons/group.svg")),
    ("fence", include_str!("../assets/icons/fence.svg")),
    ("factory", include_str!("../assets/icons/factory.svg")),
    ("squirrel", include_str!("../assets/icons/squirrel.svg")),
    ("cherry", include_str!("../assets/icons/cherry.svg")),
    ("worm", include_str!("../assets/icons/worm.svg")),
    ("hammer", include_str!("../assets/icons/hammer.svg")),
    (
        "calendar-days",
        include_str!("../assets/icons/calendar-days.svg"),
    ),
    ("file-type", include_str!("../assets/icons/file-type.svg")),
    ("medal", include_str!("../assets/icons/medal.svg")),
    (
        "radio-tower",
        include_str!("../assets/icons/radio-tower.svg"),
    ),
    ("sun", include_str!("../assets/icons/sun.svg")),
    ("car", include_str!("../assets/icons/car.svg")),
    ("sparkle", include_str!("../assets/icons/sparkle.svg")),
    ("gitlab", include_str!("../assets/icons/gitlab.svg")),
    ("magnet", include_str!("../assets/icons/magnet.svg")),
    ("unplug", include_str!("../assets/icons/unplug.svg")),
    ("cake", include_str!("../assets/icons/cake.svg")),
    ("church", include_str!("../assets/icons/church.svg")),
    ("sandwich", include_str!("../assets/icons/sandwich.svg")),
    ("carrot", include_str!("../assets/icons/carrot.svg")),
    ("flower-2", include_str!("../assets/icons/flower-2.svg")),
    ("rabbit", include_str!("../assets/icons/rabbit.svg")),
    ("hotel", include_str!("../assets/icons/hotel.svg")),
    ("school", include_str!("../assets/icons/school.svg")),
    ("container", include_str!("../assets/icons/container.svg")),
    ("pizza", include_str!("../assets/icons/pizza.svg")),
    ("tags", include_str!("../assets/icons/tags.svg")),
    ("clover", include_str!("../assets/icons/clover.svg")),
    ("github", include_str!("../assets/icons/github.svg")),
    ("layers", include_str!("../assets/icons/layers.svg")),
    ("map", include_str!("../assets/icons/map.svg")),
    ("waves", include_str!("../assets/icons/waves.svg")),
    ("pointer", include_str!("../assets/icons/pointer.svg")),
    ("atom", include_str!("../assets/icons/atom.svg")),
    ("trophy", include_str!("../assets/icons/trophy.svg")),
    ("radar", include_str!("../assets/icons/radar.svg")),
    ("rocket", include_str!("../assets/icons/rocket.svg")),
    (
        "wand-sparkles",
        include_str!("../assets/icons/wand-sparkles.svg"),
    ),
    ("beer", include_str!("../assets/icons/beer.svg")),
    ("figma", include_str!("../assets/icons/figma.svg")),
    ("tree-palm", include_str!("../assets/icons/tree-palm.svg")),
    ("cat", include_str!("../assets/icons/cat.svg")),
    ("salad", include_str!("../assets/icons/salad.svg")),
    ("ship", include_str!("../assets/icons/ship.svg")),
    ("pen-tool", include_str!("../assets/icons/pen-tool.svg")),
    ("building", include_str!("../assets/icons/building.svg")),
    ("grape", include_str!("../assets/icons/grape.svg")),
    ("sparkles", include_str!("../assets/icons/sparkles.svg")),
    ("palette", include_str!("../assets/icons/palette.svg")),
    ("unlink", include_str!("../assets/icons/unlink.svg")),
    ("soup", include_str!("../assets/icons/soup.svg")),
    ("flower", include_str!("../assets/icons/flower.svg")),
    ("settings", include_str!("../assets/icons/settings.svg")),
    ("store", include_str!("../assets/icons/store.svg")),
    ("star", include_str!("../assets/icons/star.svg")),
    ("cpu", include_str!("../assets/icons/cpu.svg")),
    (
        "codesandbox",
        include_str!("../assets/icons/codesandbox.svg"),
    ),
    ("snowflake", include_str!("../assets/icons/snowflake.svg")),
    ("brain", include_str!("../assets/icons/brain.svg")),
    ("dna", include_str!("../assets/icons/dna.svg")),
    ("bug", include_str!("../assets/icons/bug.svg")),
    ("qr-code", include_str!("../assets/icons/qr-code.svg")),
    ("cog", include_str!("../assets/icons/cog.svg")),
    ("recycle", include_str!("../assets/icons/recycle.svg")),
    ("candy", include_str!("../assets/icons/candy.svg")),
    ("telescope", include_str!("../assets/icons/telescope.svg")),
    ("croissant", include_str!("../assets/icons/croissant.svg")),
    ("fish", include_str!("../assets/icons/fish.svg")),
    ("satellite", include_str!("../assets/icons/satellite.svg")),
    ("gamepad-2", include_str!("../assets/icons/gamepad-2.svg")),
    ("puzzle", include_str!("../assets/icons/puzzle.svg")),
    ("nut", include_str!("../assets/icons/nut.svg")),
    ("dog", include_str!("../assets/icons/dog.svg")),
    ("component", include_str!("../assets/icons/component.svg")),
    ("wheat", include_str!("../assets/icons/wheat.svg")),
];

/// Search icons by case-insensitive substring match on name.
pub fn search(query: &str) -> Vec<(&'static str, &'static str)> {
    if query.is_empty() {
        return ICONS.to_vec();
    }
    let q = query.to_lowercase();
    ICONS
        .iter()
        .filter(|(name, _)| name.contains(&*q))
        .copied()
        .collect()
}

/// Look up an icon SVG by exact name.
pub fn get(name: &str) -> Option<&'static str> {
    ICONS.iter().find(|(n, _)| *n == name).map(|(_, svg)| *svg)
}

/// Default icon name used when no icon is set.
pub const DEFAULT_ICON: &str = "folder";

/// Create an SVG handle with `currentColor` replaced by white for dark themes.
pub fn svg_handle(svg_data: &str) -> iced::widget::svg::Handle {
    let white_svg = svg_data.replace("currentColor", "#e0e0e0");
    iced::widget::svg::Handle::from_memory(white_svg.into_bytes())
}
